### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jrthornham** [vishhvaan/eve-pi#1]
https://github.com/vishhvaan/eve-pi/blob/4abe5f3299e4a15edcbcd1a8bd603c1d245a2ba0/st_eve.sh#L47

cp /eve/webui/webui.service /lib/systemd/system/eve_webui.service

should be

cp /eve/webui/eve_webui.service /lib/systemd/system/eve_webui.service

**Comment by vishhvaan** [comment]
Fixed in 4ccfbe238e3cba35cde807cabff99f874dac7546
