### ISSUE TITLE
Where is the photodiode in the schematics?

### ISSUE THREAD

**Issue by CamDavidsonPilon** [vishhvaan/eve-pi#9]
Hi @vishhvaan, I'm quite new to electronics and reading circuit diagrams, so bear with me. I wasn't able to find the photodiode symbol in the schematics.pdf file. Do you mind pointing out where it is?

**Comment by vishhvaan** [comment]
Hi Cam - find the labels PD{x}_NEG and PD{x}_POS where x is the culture unit number. Connect the negative and positive terminals of the photodiode to those labels respectively.

**Comment by CamDavidsonPilon** [comment]
That's what I traced back yea, I guess I was expecting the traditional |◁ symbol, you know? 

Unrelated: How important was using an opamp for this project?

**Comment by vishhvaan** [comment]
You did not find that symbol since the schematics are meant to generate a PCB where we use a terminal block header to connect to the photodiodes.

It is possible to design a circuit without an op amp but most photodiodes circuits use a transimpedance amplifier.
